language: php

php:
    - 5.5.9
    - 5.6
    - 7.0

env:
    matrix:
        - COMPOSER_FLAGS=""
        - COMPOSER_FLAGS="--prefer-lowest"

cache:
    directories:
        - $HOME/.composer/cache/files

notifications:
    email: false

install:
    - composer self-update
    - composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit
